# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-22 21:34
from __future__ import unicode_literals
from __future__ import absolute_import

from django.db import migrations


def insert_categories(apps, schema_editor):
    Category = apps.get_model('category', 'Category')
    lista = ["Ação", "Aventura", "Comédia", "Terror", "Policial", "Romance", "Suspense"]
    for category in lista:
        Category.objects.create(name=category)


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_categories),
    ]
