# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-22 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_movie_category'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='rented_movies',
            field=models.ManyToManyField(to='movie.Movie'),
        ),
    ]
