# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-22 21:46
from __future__ import unicode_literals

from django.db import migrations


def insert_movies(apps, schema_editor):
    Category = apps.get_model('category', 'Category')
    Movie = apps.get_model('movie', 'Movie')
    movies = [
        'O Senhor dos Anéis - O Retorno do Rei', 'Vingadores: Guerra Infinita', 'Batman - O Cavaleiro Das Trevas',
        'O Senhor dos Anéis - A Sociedade do Anel', 'Velozes & Furiosos 7'
    ]
    category = Category.objects.get(name="Ação")
    for movie in movies:
        Movie.objects.create(name=movie, quantity=5, rented=0, category=category)


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_movie_category'),
    ]

    operations = [
        migrations.RunPython(insert_movies)
    ]
