# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-23 03:49
from __future__ import unicode_literals

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_insert_movies'),
    ]

    operations = [
    ]
